# conda env create --file environment.yml
# mamba env create --file environment.yml
# conda env export --from-history > environment.yml
# conda env export --no-builds > environemnt.yml
# conda env update --file environment.yml

# pip install optbinning
# pip install ortools==9.6.2534
# pip install --upgrade cvxpy
# pip install varclushi

name: ml2
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - alembic=1.8.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=3.2.4
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - black=24.8.0
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - catboost=1.2.3
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - colorlog=5.0.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dacite=1.8.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - executing=0.8.3
  - expat=2.6.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fs=2.4.16
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - graphviz=2.50.0
  - greenlet=3.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gts=0.7.6
  - h11=0.14.0
  - harfbuzz=4.3.0
  - htmlmin=0.1.12
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - imagehash=4.3.1
  - invoke=1.6.0
  - ipykernel=6.28.0
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.9.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.17
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxgboost=2.1.1
  - libxml2=2.13.1
  - lightgbm=4.5.0
  - llvm-openmp=14.0.6
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - mako=1.2.3
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - missingno=0.4.2
  - mistune=2.0.4
  - multimethod=1.9.1
  - multipledispatch=0.6.0
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - natsort=7.1.1
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbdime=4.0.1
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - optuna=4.0.0
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandas-flavor=0.6.0
  - pandas_flavor=0.6.0
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pathspec=0.10.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - phik=0.12.3
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - plotly=5.22.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=2.1.1
  - pybind11-abi=4
  - pycparser=2.21
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.15.1
  - pyjanitor=0.28.1
  - pylint=3.2.7
  - pyparsing=3.0.9
  - pyprojroot=0.3.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - smmap=4.0.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - tbb=2021.8.0
  - tenacity=8.2.3
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomlkit=0.11.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typeguard=4.2.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - visions=0.7.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - wordcloud=1.9.3
  - xarray=2023.6.0
  - xgboost=2.1.1
  - xlrd=2.0.1
  - xz=5.4.6
  - yaml=0.2.5
  - ydata-profiling=4.8.3
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - clarabel==0.9.0
      - cvxpy==1.5.3
      - ecos==2.0.14
      - factor-analyzer==0.3.1
      - imbalanced-learn==0.12.3
      - imblearn==0.0
      - immutabledict==4.2.0
      - optbinning==0.19.0
      - ortools==9.6.2534
      - osqp==0.6.7.post1
      - protobuf==5.28.1
      - qdldl==0.1.7.post4
      - ropwr==1.0.0
      - scs==3.2.7
      - varclushi==0.1.0
