# conda env create --file environment.yml
# mamba env create --file environment.yml
# conda env export --from-history > environment.yml

name: ML2
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - black
  - pylint
  - invoke
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - python-dotenv
  - pyprojroot
  - fs
  - nbdime
  - numpy
  - pandas
  - pyjanitor
  - matplotlib
  - seaborn
  - missingno
  - pandas-flavor
  - ydata-profiling
  - lightgbm
  - catboost
  - xgboost
  - optuna
  - statsmodels
  - scikit-learn
  - scipy
  - pip:
    - optbinning
    - varclushi
    - ortools==9.6.2534
    - cvxpy
    - imblearn